# 基本服务配置
port: 7003

# 日志配置
log:
  level: debug
  directory: out/log/

# 临时目录
tmp-dir: out/tmp

# 监听任务配置
watchers:
  # XML(Export)监听配置
  export:
    enabled: true  # 是否启用Export监听
    nl:
      enabled: true  # 是否启用荷兰Export监听
      watch-dir: out/watch/nl
      backup-dir: out/backup/nl
    be:
      enabled: true  # 是否启用比利时Export监听  
      watch-dir: out/watch/be
      backup-dir: out/backup/be
  
  # PDF(税金单)监听配置
  pdf:
    enabled: false  # 是否启用PDF监听
    nl:
      enabled: true  # 是否启用荷兰PDF监听
      watch-dir: out/watch-pdf/nl
      backup-dir: out/pdf/nl
    be:
      enabled: true  # 是否启用比利时PDF监听
      watch-dir: out/watch-pdf/be
      backup-dir: out/pdf/be

# 目录存储配置，用于web server下载文件等
storage:
  nl:
    tax-bill: out/pdf/nl
    export: out/backup/nl
  be:
    tax-bill: out/pdf/be
    export: out/backup/be

# import xml 保存路径
import:
  xml-dir: out/import-20250428

# 文件移动队列配置
# 注意：
# 1. 系统繁忙时，文件的移动处理会阻塞，因此考虑异步处理
# 2. 也就是所有涉及到文件系统中文件修改路径的操作，都应该放入此队列中交由异步队列处理
file-mover:
  enabled: true # 是否启用荷兰文件移动队列
  queue-size: 500 # 队列缓冲大小，当系统繁忙时可缓存等待处理的文件移动任务
  queue-name: global_async_file_mover # 队列名称，用于日志标识
  worker-count: 2 # 并发工作进程数量

# RabbitMQ配置
rabbitmq:
  url: amqp://guest:guest@rabbitmq:5672
  # 连接设置
  heartbeat: 10s
  connection-timeout: 30s
  # 连接池设置
  max-connections: 3
  max-channels-per-conn: 10
  # 自动恢复设置
  auto-reconnect: true
  reconnect-interval: 5s
  # 消费者设置
  prefetch-count: 1
  auto-ack: false
  # 导入XML队列
  import:
    consumer: asl_import_xml_consumer_dev
    exchange: softpak.import.topic
    exchange-type: topic
    queue: softpak.import
  # 导出XML队列
  export:
    exchange: softpak.export.topic
    exchange-type: topic
    queue: softpak.export
