# file server port
port: 7003

# Log path and level
log:
  level: debug
  directory: out/log/

# The saving path of tax bills and export files
ser-dir:
  nl:
    tax-bill: out/pdf/nl
    export: out/backup/nl
  be:
    tax-bill: out/pdf/be
    export: out/backup/be

# Import XML save directory
import:
  xml-dir: out/import-20250428

# Export XML file listening path
watcher:
  nl:
    watch-dir: out/watch/nl
    backup-dir: out/backup/nl
  be:
    watch-dir: out/watch/be
    backup-dir: out/backup/be

# Temporary path
tmp-dir: out/tmp

# Queue size for file remover
remover:
  queue_size: 200

# RabbitMQ configuration
rabbitmq:
  url: amqp://guest:guest@rabbitmq:5672
  # Connection settings
  heartbeat: 10s
  connection-timeout: 30s
  # Connection pool settings
  max-connections: 3
  max-channels-per-conn: 10
  # Auto recovery settings
  auto-reconnect: true
  reconnect-interval: 5s
  # Consumer settings
  prefetch-count: 1
  auto-ack: false
  # Import xml queue
  import:
    # consumer_name
    consumer: asl_import_xml_consumer_dev
    exchange: softpak.import.topic
    exchange-type: topic
    queue: softpak.import
  # Export xml queue
  export:
    exchange: softpak.export.topic
    exchange-type: topic
    # queue prefix: softpak.export.be / softpak.export.nl
    queue: softpak.export
