package cmd

import (
	"fmt"

	log "github.com/sirupsen/logrus"
	_ "sysafari.com/softpak/rattler/docs" // docs is generated by Swag CLI, you have to import it.
	"sysafari.com/softpak/rattler/internal/component"
	"sysafari.com/softpak/rattler/internal/config"
	"sysafari.com/softpak/rattler/internal/service"
	"sysafari.com/softpak/rattler/internal/util"
)

// 全局文件事件处理器（按国家分别创建）
var (
	exportXmlProcessors map[string]*component.FileProcessor // key: country
	taxBillProcessors   map[string]*component.FileProcessor // key: country
)

// FileHandler 定义文件处理函数类型
type FileHandler func(filename string, country string) error

// 处理Export XML文件创建事件
func handleExportXmlCreateEvent(filename string, country string) error {
	log.Infof("处理 %s 申报国家的 Export XML 文件: %s", country, filename)

	if !util.IsExists(filename) {
		log.Errorf("触发监听的文件不存在，请检查是否手动移除了此文件: %s", filename)
		return fmt.Errorf("触发监听的文件不存在，请检查是否手动移除了此文件: %s", filename)
	}

	service.SendExportXml(filename, country)
	return nil
}

// 处理税单创建事件
func handleTaxBillCreateEvent(filename string, country string) error {
	log.Infof("处理 %s 税单文件: %s", country, filename)

	if !util.IsExists(filename) {
		log.Errorf("触发监听的文件不存在，请检查是否手动移除了此文件: %s", filename)
		return fmt.Errorf("触发监听的文件不存在，请检查是否手动移除了此文件: %s", filename)
	}

	taxBillService := service.NewTaxBillService()
	_, err := taxBillService.MoveTaxBillToBackup(filename, country)
	if err != nil {
		log.Errorf("备份 %s 的税金单文件 %s 失败: %v", country, filename, err)
		return fmt.Errorf("备份 %s 的税金单文件 %s 失败: %v", country, filename, err)
	}

	return nil
}

// 启动文件监听器（新架构：使用事件通道解耦监听和处理）
func startFileWatcher(dir string, country string, filePattern string, fileType string, handler FileHandler) {
	log.Infof("开始监控 %s 申报国家的%s文件目录: %s", country, fileType, dir)

	// 确保监控目录存在
	if !util.IsDir(dir) {
		log.Panicf("监控目录: %s 不存在或不是目录，请检查配置", dir)
	}

	// 事件通道：基础 1000 + 临时 500，长度不够时可容纳更多事件不丢
	eventChannelSize := component.EventChannelBaseSize + component.EventChannelExtraSize
	eventChannel := make(chan component.FileEvent, eventChannelSize)
	log.Infof("事件通道已创建，容量: %d (基础 %d + 临时 %d)", eventChannelSize, component.EventChannelBaseSize, component.EventChannelExtraSize)

	// 处理文件创建事件的包装函数，转换参数类型
	handlerWrapper := func(filename string, additionalData interface{}) error {
		return handler(filename, additionalData.(string))
	}

	// 文件处理器配置：单队列按序消费（等可读 → 读 → 发）
	processorConfig := component.FileProcessorConfig{
		EventChannel:   eventChannel,
		Handler:        handlerWrapper,
		JobNoExtractor: component.ExtractBusinessKeyFromFileName, // 提取Job No，仅用于日志
		WaitTime:       5,                                        // 文件写入完成等待时间
		MaxRetries:     10,                                       // 最大重试次数
		MinFileSize:    100,                                      // 文件最小大小100字节
	}

	// 创建并启动文件处理器
	processor := component.NewFileProcessor(processorConfig)
	processor.Start()

	// 保存处理器引用（用于后续停止）
	switch fileType {
	case "XML":
		if exportXmlProcessors == nil {
			exportXmlProcessors = make(map[string]*component.FileProcessor)
		}
		exportXmlProcessors[country] = processor
	case "税单":
		if taxBillProcessors == nil {
			taxBillProcessors = make(map[string]*component.FileProcessor)
		}
		taxBillProcessors[country] = processor
	}

	// 创建FSWatcher配置（使用事件通道模式）
	watcherConfig := component.FSWatcherConfig{
		Dir:            dir,
		Operations:     component.Create, // 只监听创建事件
		FilePattern:    filePattern,      // 文件后缀格式(如: .xml)匹配模式
		EventChannel:   eventChannel,     // 使用事件通道（解耦模式）
		AdditionalData: country,          // 传递申报国家信息
		WatchSubdirs:   config.GlobalConfig.Watchers.WatchSubdirs,
	}

	watcher := component.NewFSWatcher(watcherConfig)
	err := watcher.Start()
	if err != nil {
		log.Errorf("启动 %s 申报国家的%s文件监听失败: %v", country, fileType, err)
	} else {
		log.Infof("成功启动 %s 申报国家的%s文件监听（新架构：事件通道模式）", country, fileType)
	}
}

// StartWatchExportXmlDirWorker 启动Export XML文件监听
func StartWatchExportXmlDirWorker() {
	if !config.GlobalConfig.Watchers.Export.Enabled {
		return
	}

	log.Info("开启 Export XML 文件监听 ...")

	// 监听NL国家的Export XML文件
	if config.GlobalConfig.Watchers.Export.NL.Enabled {
		startFileWatcher(
			config.GlobalConfig.Watchers.Export.NL.WatchDir,
			"NL",
			".*\\.xml",
			"XML",
			handleExportXmlCreateEvent,
		)
	}

	// 监听BE国家的Export XML文件
	if config.GlobalConfig.Watchers.Export.BE.Enabled {
		startFileWatcher(
			config.GlobalConfig.Watchers.Export.BE.WatchDir,
			"BE",
			".*\\.xml",
			"XML",
			handleExportXmlCreateEvent,
		)
	}
}

const (
	// TaxBillFilePattern 税单文件匹配模式, 不区分 pdf，PDF, Pdf 等大小写
	TaxBillFilePattern = ".*\\.(?i)pdf$"
)

// StartWatchTaxBillDirWorker 启动税单文件监听
func StartWatchTaxBillDirWorker() {
	if !config.GlobalConfig.Watchers.Pdf.Enabled {
		return
	}

	log.Info("开启税单文件监听 ...")

	// 监听NL国家的税单文件
	if config.GlobalConfig.Watchers.Pdf.NL.Enabled {
		startFileWatcher(
			config.GlobalConfig.Watchers.Pdf.NL.WatchDir,
			"NL",
			TaxBillFilePattern,
			"税单",
			handleTaxBillCreateEvent,
		)
	}

	// 监听BE国家的税单文件
	if config.GlobalConfig.Watchers.Pdf.BE.Enabled {
		startFileWatcher(
			config.GlobalConfig.Watchers.Pdf.BE.WatchDir,
			"BE",
			TaxBillFilePattern,
			"税单",
			handleTaxBillCreateEvent,
		)
	}
}
