package cmd

import (
	log "github.com/sirupsen/logrus"
	_ "sysafari.com/softpak/rattler/docs" // docs is generated by Swag CLI, you have to import it.
	"sysafari.com/softpak/rattler/internal/config"
	"sysafari.com/softpak/rattler/internal/service"
	"sysafari.com/softpak/rattler/internal/util"
)

// 监听Export XML文件
func watchExportXmlDir(dir string, declareCountry string) {
	log.Infof("开始监控 %s 申报国家的 XML 文件目录: %s", declareCountry, dir)

	// 确保监控目录存在
	if !util.IsDir(dir) {
		log.Panicf("监控目录: %s 不存在或不是目录，请检查配置", dir)
	}

	service.Watch(dir, declareCountry)
}

// StartWatchExportXmlDirWorker 启动Export XML文件监听
// 根据配置文件中的监听配置，分别启动NL和BE国家的Export XML文件监听
func StartWatchExportXmlDirWorker() {
	if config.GlobalConfig.Watchers.Export.Enabled {
		log.Info("开启 Export XML 文件监听 ...")

		// 监听NL国家的Export XML文件
		if config.GlobalConfig.Watchers.Export.NL.Enabled {
			go watchExportXmlDir(config.GlobalConfig.Watchers.Export.NL.WatchDir, "NL")
		}

		// 监听BE国家的Export XML文件
		if config.GlobalConfig.Watchers.Export.BE.Enabled {
			go watchExportXmlDir(config.GlobalConfig.Watchers.Export.BE.WatchDir, "BE")
		}

	}
}

// StartMoveFileWorker 启动文件移动处理程序
func StartMoveFileWorker() {
	// 初始化NL国家的文件移动处理程序
	if config.GlobalConfig.FileMover.Enabled {
		config.InitFileMover()
	}

}
